"""Constantes de la máquina de estados para la conversación del bot."""

PIDIENDO_PRODUCTO = 1
PIDIENDO_CANTIDAD = 2
PIDIENDO_TIPO_ENTREGA = 3
PIDIENDO_METODO_PAGO = 4
PIDIENDO_COMPROBANTE = 5
CONFIRMANDO_PEDIDO = 6
PIDIENDO_UBICACION = 7
ESPERANDO_COSTO_DELIVERY = 8
PIDIENDO_MODO_PRECIO = 9
PIDIENDO_NOMBRE_CLIENTE = 10
PIDIENDO_CEDULA_CLIENTE = 11
PIDIENDO_TELEFONO_CLIENTE = 12
